spring.datasource.url=jdbc:postgresql://localhost:5433/eimt_lab
spring.datasource.username=emc
spring.datasource.password=emc

spring.jpa.hibernate.ddl-auto=validate

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
